using System;
using System.Text.RegularExpressions;
using BackEndAPI.Interfaces;

namespace BackEndAPI.Helpers
{
    public static class AutoGenerator
    {

        public static string AutoGeneratedStaffCode(int id)
        {
            if (id <= 0)
            {

                throw new InvalidOperationException(Message.InvalidId);

            }

            return $"SD{id.ToString("D4")}";

        }

       public static string AutoGeneratedUsername(string firstName, string lastName)
		{

			if (string.IsNullOrWhiteSpace(firstName) || string.IsNullOrWhiteSpace(lastName))
			{

				throw new ArgumentException();

			}

			string firstNameRegex = Regex.Replace(firstName, @"\s+", " ").Trim();
			string lastNameRegex = Regex.Replace(lastName, @"\s+", " ").Trim();

			if (string.IsNullOrWhiteSpace(firstNameRegex) || string.IsNullOrWhiteSpace(lastNameRegex))
			{

				throw new Exception();

			}


			string name = $"{firstNameRegex.ToLower()} {lastNameRegex.ToLower()}";
			string shortName = string.Empty;

			string[] nameParts = name.Trim().Split(' ');

			for (var index = 0; index < nameParts.Length; index++)
			{
				var part = nameParts[index];
				if (index == 0)
					shortName += part;
				else
				{
					shortName += part.Substring(0, 1);
				}
			};
			return shortName;
		}

        public static string AutoGeneratedPassword(string username, DateTime dob)
        {
            if (username == null || username == "")
            {

                throw new ArgumentNullException(Message.NullOrEmptyUsername);

            }

            return $"{username}@{dob.Date.ToString("ddMMyyyy")}";

        }

        public static string AutoGeneratedAssetCode(int assetNumber, string prefix)
        {

            if (assetNumber < 0)
            {

                throw new InvalidOperationException(Message.AssetNumberError);

            }

            if (prefix == null)
            {

                throw new ArgumentNullException(Message.NullOrEmptyPrefix);

            }

            prefix = Regex.Replace(prefix, @"\s+", " ").Trim();

            if (prefix == "")
            {

                throw new ArgumentNullException(Message.NullOrEmptyPrefix);

            }

            return $"{prefix}{(assetNumber + 1).ToString("D6")}";

        }

    }
}
